# Site settings
title: SherSec
email: shersec@machproductions.com
description: > # this means to ignore newlines until "baseurl:"
  A local group that meets up to discuss anything technical

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://SherSec.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  shersec

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Local geeks"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""

github_repository: https://github.com/SherSec/shersec.github.io
github_username:  SherSec/shersec.github.io
post_limit: 4